Installation updates
WANdisco/wandisco-documentation-ldm pull request #10
Opened 2020-08-18 16:09 UTC by benradstone

2020-08-18 16:10 UTC, benradstone commented on docs/installation.md
> +Choose your preferred interface below to get started:
Not sure about this line, can be changed if needed.

2020-08-19 09:04 UTC, shonaisbister-disco commented on docs/installation.md
> +    * You will need to be able to authenticate as the [HDFS superuser](https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/HdfsPermissionsGuide.html#The_Super-User) (for example: `
Line 22: update 'you will need to be able to..' (wordy) to 'Ability to authenticate...'

2020-08-19 09:06 UTC, shonaisbister-disco commented on docs/installation.md
> +This will start LiveData Migrator and the action prompt will appear.
Line 73: present tense, so the action prompt appears (not will appear)

2020-08-19 09:09 UTC, shonaisbister-disco commented on docs/installation.md
> +If Kerberos is enabled in your environment, then prior to running the `livedata-migrator.jar`, you must obtain a Kerberos ticket for the HDFS superuser principal.
Line 77: this reads awkwardly. Rewrite, something like 

If Kerboros is enabled in your environment, make sure you get a Kerberos ticket for the HDFS superuser principal before running 'livedata-migrator.jar'.

2020-08-19 09:11 UTC, shonaisbister-disco commented on docs/installation.md
> +The required properties are detailed in the [Kerberos Integration](./configuration.md#kerberos-integration) section.
Line 106: Make active 'Refer to [link] for details about the required properties.'

2020-08-19 09:12 UTC, shonaisbister-disco commented on docs/installation.md
> +You can stop the service at any time using:
Line 114: remove a couple of extra words: 'Stop the service with:'

(or make it consistent with the start service instruction by adding 'stop the service with the init script' or whatever is relevant here!

2020-08-19 09:13 UTC, shonaisbister-disco commented on docs/installation.md
> +The configuration properties for SSH are listed in the [SSH access](./configuration.md#ssh-access) section.
Line 130: as above, make active with 'Refer to xyz for details about the configuration properties'.

2020-08-19 09:13 UTC, shonaisbister-disco commented on docs/installation.md
> +This will start LiveData Migrator and the action prompt will appear.
Line 143: 'appears' not 'will appear'

2020-08-19 09:14 UTC, shonaisbister-disco commented on docs/installation.md
> +Choose your preferred interface below to get started:
Line 156? I think it's fine!

2020-08-19 09:15 UTC, shonaisbister-disco requested changes
I think this improves the page a lot! Looks great. Just a few comments to tidy up instructions, ensuring it's active and in the present tense.

2020-08-19 09:47 UTC, merged