Documented non-live migrations in UI
WANdisco/wandisco-documentation-ldm pull request #130
Opened 2021-01-19 14:32 UTC by stepgerner

Instead of continuing to add on to a progressively lengthening "create a migration" page, I added a separate "create a non-live migration" page and moved all of the CLI info over before adding the UI info.

2021-01-19 18:00 UTC, shonaisbister-disco commented on docs/create-migration.md
> +It's possible to create a migration that does not track client activity: if files are changed during the migration process, they will not be re-scanned by LiveData Migrator.
Line 59: I think this is quite hard to understand. Can you simplify? Also, write it actively (start with 'create a migration that does not track client activity...') and avoid colons in the middle of text like this and define non-live so it's tied nicely to the heading and makes sense to the user.

Something like: 'Create a non-live migration if you don't want LiveData Migrator to scan for changes in your data while it is being migrated.'  Feel free to add more context! But you get the gist.

Also, do we definitely want to talk about 'non-live' as a term we expect users to get onboard with? Might be worth checking with Product on that one.

2021-01-19 18:03 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +A non-live migration is a migration that does not track client activity: if files are changed during the migration process, they will not be re-scanned by LiveData Migrator.
Line 7 - take out the colon and make another sentence.  Also 'client acitvity' isn't how a customer would think of it - they ARE the client in this case. 'A non-live migration is a migration that doesn't track your activity to files being migrated. LiveData Migrator won't scan your data for updates during non-live migrations.'

2021-01-19 18:05 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +A non-live migration does not track events from the source file system, and does not write a [marker file](./configuration-ldm.md/#hdfs-marker-storage) to the source file system. Once the scan of the
Line 10: clean up the ending which is a bit awkward: ....'and won't perform any further scans' or similar.

2021-01-19 18:05 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +Non-live migrations may be created through the UI or through the CLI.
Line 17: Make active 'Create a non-live migration with either the UI or CLI'

2021-01-19 18:06 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +To create a non-live migration through the CLI, simply deselect the "Live Migration" option when creating a migration. Unlike a live migration, this migration will not state that it is live. When in
Line 21: 'with' the CLI (not 'through')

2021-01-19 18:08 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +To create a non-live migration through the CLI, simply deselect the "Live Migration" option when creating a migration. Unlike a live migration, this migration will not state that it is live. When in
Also, take out the 'simply'. I think the second sentence is redundant so take that out too (they're deliberately creating a 'non-live' migration here and have de-selected the checkbox).

Style thing: write in the present tense. So 'the migration will inform you' becomes 'the migration tells you to rerun the migration to see changes/updates/whatever'.

2021-01-19 18:08 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +A non-live migration is a migration that does not track client activity: if files are changed during the migration process, they will not be re-scanned by LiveData Migrator. There are two ways to cre
Line 25: See earlier comments about this, and update to the same.

2021-01-19 18:09 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +1. Specify the `scanOnly` flag during migration creation:
Line 28: is that a zero or an O? Musing!

2021-01-19 18:09 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +A non-live migration does not read events from the source file system, and does not write a [marker file](./configuration-ldm.md/#hdfs-marker-storage) to the source file system. Once the scan of the
Line 35: See earlier comments about this, and update accordingly.

2021-01-19 18:11 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +Any migration created from a non-live source via the CLI will become a non-live migration by default, whereas the UI will uncheck the "live migration" option by default and prevent it from being enab
Line 43: Style thing: no Latin. Replace 'via' with 'with'. Also, this is quite confusing. The UI and CLI are both setting the migration to non-live by default if a non-live source is detected, but your sentence explaining how it actually does this confuses it. Can you clarify? Maybe separate out the info about the 'live migration' option being de-selected?

2021-01-19 18:12 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +To create a non-live source, simply uncheck the "Migrate Live Events" box during source creation.
Line 50: remove 'simply'

2021-01-19 18:13 UTC, shonaisbister-disco requested changes
Pretty good! A few style tweaks needed here and a bit of clarification.

2021-01-20 11:41 UTC, stepgerner commented on docs/create-migration.md
> +It's possible to create a migration that does not track client activity: if files are changed during the migration process, they will not be re-scanned by LiveData Migrator.
Last I heard, we were still deciding on what to call some of the options featuring non-live migrations. I'll consider them non-live migrations for now, and update them later if needbe, possibly in a separate ticket. But I'll check with product anyway to be sure.

Do you know anyone in the team I should contact? I don't know the product team at all unfortunately.

2021-01-20 11:56 UTC, stepgerner commented on docs/non-live-migration.md
> +Non-live migrations may be created through the UI or through the CLI.
Small nitpick here, telling someone to do something in this context (where they're not literally sitting in front of the button) feels a little unnatural to me. I feel like this particular segment is intended to be informational rather than a call to action.

I welcome contradiction on that one though

2021-01-20 11:57 UTC, stepgerner commented on docs/non-live-migration.md
> +To create a non-live migration through the CLI, simply deselect the "Live Migration" option when creating a migration. Unlike a live migration, this migration will not state that it is live. When in
Haha woops, that was my old "video voice" talking when I said "simply"

I understand. Thanks for the feedback.

2021-01-20 12:03 UTC, stepgerner commented on docs/non-live-migration.md
> +A non-live migration is a migration that does not track client activity: if files are changed during the migration process, they will not be re-scanned by LiveData Migrator. There are two ways to cre
I will simply delete this segment (up to "There are two ways...") as I now realise its redundancy.

2021-01-20 12:04 UTC, stepgerner commented on docs/non-live-migration.md
> +1. Specify the `scanOnly` flag during migration creation:
It's an O. Gotta love having fonts that make totally different characters look identical.

2021-01-20 12:42 UTC, shonaisbister-disco commented on docs/create-migration.md
> +It's possible to create a migration that does not track client activity: if files are changed during the migration process, they will not be re-scanned by LiveData Migrator.
You know, I would pose the question in the docs channel. That's as much a place for us to ask people stuff as the other way around. Virginia and others are in that channel if you @here.

Will you make the rest of the changes? I think this is quite important to simplify. We should definitely avoid colons in the middle of sentences also.

2021-01-20 12:44 UTC, shonaisbister-disco commented on docs/non-live-migration.md
> +Non-live migrations may be created through the UI or through the CLI.
Why wouldn't the user be sitting in front of the software when they read this? I don't think they'll be reading through it all before actually doing it - they'll be referring to the docs to find out what to do?

2021-01-20 13:31 UTC, stepgerner commented on docs/non-live-migration.md
> +A non-live migration does not read events from the source file system, and does not write a [marker file](./configuration-ldm.md/#hdfs-marker-storage) to the source file system. Once the scan of the
Sorry, I wasn't sure what specifically you meant here, so I just performed general improvement/simplification.

2021-01-20 14:23 UTC, shonaisbister-disco approved these changes
Looks great! Like the improvements.

2021-01-20 14:28 UTC, merged