Path mapping with the CLI
WANdisco/wandisco-documentation-ldm pull request #151
Opened 2021-02-04 19:22 UTC by benradstone

2021-02-08 13:10 UTC, lucasdigital approved these changes
Just one small comment, which may not apply in a bigger context.

2021-02-08 13:10 UTC, lucasdigital commented on docs/command-reference.md
> +Create a path mapping that allows you to define separate target path for a specific target filesystem. These will be automatically applied to a new migration.
Should this be "separate target paths" or more likely "define a separate target path..."?

2021-02-08 13:28 UTC, benradstone commented on docs/command-reference.md
> +Create a path mapping that allows you to define separate target path for a specific target filesystem. These will be automatically applied to a new migration.
Yes, it should!

2021-02-08 15:14 UTC, benradstone commented on docs/create-path-mappings.md
> +## Path mapping limitation
@lucasdigital Added this *Path mapping limitation* section, could you give it a once over?

2021-02-08 15:22 UTC, lucasdigital approved these changes
LGTM

2021-02-12 11:24 UTC, shonaisbister-disco commented on docs/command-reference.md
> +Create a path mapping that allows you to define a separate target path for a specific target filesystem. These will be automatically applied to a new migration.
Line 829: separate, or alternative?

2021-02-12 11:25 UTC, shonaisbister-disco commented on docs/command-reference.md
> +Create a path mapping that allows you to define a separate target path for a specific target filesystem. These will be automatically applied to a new migration.
Or make it clear that they're changing the default path.

2021-02-12 11:26 UTC, shonaisbister-disco commented on docs/command-reference.md
> +Deleting a path mapping will not affect any existing migrations that have the path mapping applied. Delete and recreate a migration if you no longer want a previous path mapping to apply.
Line 868: Holy cow really?! What a pain for customers.

2021-02-12 11:27 UTC, shonaisbister-disco commented on docs/configure-storage.md
> +If you want to exclude specific file sizes or file names from your data migrations, [define exclusions](./configure-exclusions.md) as well.
Line 137: remove 'as well'.

2021-02-12 11:28 UTC, shonaisbister-disco commented on docs/create-path-mappings.md
> +Create path mappings when you want your target filesystem to store the migrated data in a different path to that of your source filesystem.
Line 7: is data stored in a different path? Or in a different directory?

2021-02-12 11:28 UTC, shonaisbister-disco commented on docs/create-path-mappings.md
> +Create path mappings when you want your target filesystem to store the migrated data in a different path to that of your source filesystem.
Also remove 'that of'

2021-02-12 11:29 UTC, shonaisbister-disco commented on docs/create-path-mappings.md
> +When path mapping is not used, the source path on your source filesystem will be created on your target filesystem. This may not always be suitable for the purposes of your migration.
Line 11: is it a 'default' path? I might be totally wrong here.

2021-02-12 11:33 UTC, shonaisbister-disco commented on docs/create-path-mappings.md
> +The example below presents a common use-case, the default [Hive metastore warehouse directory](https://cwiki.apache.org/confluence/display/Hive/Configuration+Properties#ConfigurationProperties-hive.m
Line 13: Clean this up a bit. "The following example shows a common use-case where the default Hive metastore warehouse directory for Hortonworks is xyz, which is xyz for Azure HDInsight." or similar.

2021-02-12 11:35 UTC, shonaisbister-disco commented on docs/create-path-mappings.md
> +Using path mapping will allow any migrated data (relating to managed Hive databases and tables) to be stored in the equivalent default location on the target.
Line 20: Not sure about 'allow'. Enables?

2021-02-12 11:37 UTC, shonaisbister-disco commented on docs/create-path-mappings.md
> +## Create a path mapping with the UI
I think remove this section altogether. You should say in the intro that it is only available in the CLI and leave it at that. I don't know if I've said this explicitly as our style, but we should also go with the positive e.g. 'Stop migrations' rather than 'Don't keep migrations running' (stupid example but hopefully illustrates my point!).

So here, say what we can do - configure path mapping in the CLI - rather than pointing out what we can't.

2021-02-12 11:40 UTC, shonaisbister-disco commented on docs/uc-on-prem-hadoop-hdi.md
> +Doing so will allow you to start using your source data and metadata on your HDInsights cluster immediately after migration, as it will be referenced correctly by your target metastore.
Line 63: Clean up the start by replacing 'Doing so will allow you' with 'This enables you...'

2021-02-12 11:40 UTC, shonaisbister-disco commented on docs/uc-on-prem-hadoop-hdi.md
> +Doing so will allow you to start using your source data and metadata on your HDInsights cluster immediately after migration, as it will be referenced correctly by your target metastore.
Or This lets you, or this means that.....

2021-02-12 11:40 UTC, shonaisbister-disco requested changes
A few style updates! Looks good.

2021-02-12 11:48 UTC, benradstone commented on docs/command-reference.md
> +Create a path mapping that allows you to define a separate target path for a specific target filesystem. These will be automatically applied to a new migration.
I prefer alternative, so will change.

2021-02-12 11:50 UTC, benradstone commented on docs/command-reference.md
> +Create a path mapping that allows you to define a separate target path for a specific target filesystem. These will be automatically applied to a new migration.
Added a little extra to explain behaviour when path mapping is not used.

2021-02-12 11:51 UTC, benradstone commented on docs/command-reference.md
> +Deleting a path mapping will not affect any existing migrations that have the path mapping applied. Delete and recreate a migration if you no longer want a previous path mapping to apply.
It's kind of a protective measure, so that users don't accidentally affect an ongoing migration.

2021-02-12 11:56 UTC, benradstone commented on docs/create-path-mappings.md
> +Create path mappings when you want your target filesystem to store the migrated data in a different path to that of your source filesystem.
I've rewritten this to be more inline with the command reference changes.

2021-02-12 11:57 UTC, benradstone commented on docs/create-path-mappings.md
> +When path mapping is not used, the source path on your source filesystem will be created on your target filesystem. This may not always be suitable for the purposes of your migration.
I don't think 'default' is the correct term here, as it is user-defined and doesn't exist as a "default".

2021-02-12 12:05 UTC, benradstone commented on docs/create-path-mappings.md
> +## Create a path mapping with the UI
I've taken on board what you've said, but we now know that path mapping in the UI is coming for this release, so I will leave this as a placeholder for that work.

2021-02-12 12:10 UTC, merged