DOCU-1089 and 1088
WANdisco/wandisco-documentation-ldm pull request #210
Opened 2021-04-27 13:45 UTC by stepgerner

Based on https://jira.wandisco.com/browse/DOCU-1088 and https://jira.wandisco.com/browse/DOCU-1089

I had no clue where to put this stuff honestly, and thought about it for a very long time. I think it's best as its own page, but notifications will require its own page too.

The "email notifications" links are just placeholders, and will be updated when I document that next.

2021-04-27 13:56 UTC, shonaisbister-disco requested changes
Hey, reads pretty well, some minor updates is all. I'm not sure about the placement of the content but think it's good enough for UAT in develop for now! Likely it's fine, but will see how it looks before suggesting anything different.

Good job!

2021-04-27 13:56 UTC, shonaisbister-disco commented on docs/configure-smtp.md
> +Configuring a connection to an SMTP server for LiveData Migrator allows the use of [email notifications](./configuration-ui.md), which notify the user via email when certain events occur in LiveData
Line 9 - tiny thing but avoid Latin abbreviations altogether. In this case, swap via for by.

2021-04-27 13:56 UTC, shonaisbister-disco commented on docs/configure-smtp.md
> +1. Click on the LiveData Migrator instance name (e.g. "localhost") on the dashboard to access the overview page.
Line 16-18 Format any buttons - like Save and SMTP Settings - in bold.

2021-04-27 13:56 UTC, shonaisbister-disco commented on docs/configure-smtp.md
> +title: Configuring an SMTP server
Line 3 - we need to make it more human for users than SMTP. They're doing it to enable email notifications, so this heading (and probably sidebar) should reflect that e.g. Set up email notifications or similar.

Then your intro sentence would, for context, start something like 'configure an SMTP server to enable email notifications....' etc.

2021-04-28 11:56 UTC, benradstone commented on docs/configure-smtp.md
> +## Email Notifications
Delete this heading and change the title above to "Configure Email Notifications".

Also consider changing "Notifications" to "Email notifications".

2021-04-28 11:56 UTC, benradstone commented on docs/configure-smtp.md
> +1. [Configure an SMTP server to send the emails](#configure-an-smtp-server)
This link looks wrong as you've got "in the UI" or "through the CLI" now.

2021-04-28 11:57 UTC, benradstone commented on docs/configure-smtp.md
> +1. [Opt in to the desired notifications](#opt-in-to-email-notifications)
Line 14: Not sure where this link is going either.

2021-04-28 12:03 UTC, benradstone commented on docs/configure-smtp.md
> +## Configure Notification Properties
This section should either be copied or moved into the LDM configuration page.

2021-04-28 12:09 UTC, stepgerner commented on docs/configure-smtp.md
> +1. [Configure an SMTP server to send the emails](#configure-an-smtp-server)
Very perceptive, thank you!

2021-04-28 12:12 UTC, merged