Update manage-migrations.md
WANdisco/wandisco-documentation-ldm pull request #271
Opened 2021-09-06 15:48 UTC by lucasdigital

The first draft for DOCU-1268, to be merged into master, as agreed.

2021-09-06 16:23 UTC, AshVic requested changes
Few wee changes

2021-09-06 16:23 UTC, AshVic commented on docs/manage-migrations.md
> +#### Filter and Search Failed Operations
Other headers in this topic use sentence style so would suggest for consistency; 
"Filter and search for failed operations" (with the addition of the word "for")

2021-09-06 16:23 UTC, AshVic commented on docs/manage-migrations.md
> +Filter or search for failed operations by using the *Operation type* drop-down selector on the Migration Check Report panel. The filter contains the following operations:
I am not sure if we are to use italics for this "Operation type". It looks like our style guide states we should use bold font.
https://workspace.wandisco.com/pages/viewpage.action?pageId=63733822
Therefore, we should use bold for the following:
- Operation type (if this is how it is written on the UI) - I can only see the wireframe which seems to call it "Operation"?
- Migration Check Report (if that is what appears on the UI) - the wireframe calls it "Migration Check" - sorry I can't access the current UI.

Another style point is that the style guide references the MS style guide and the term used is "dropdown" (without selector): https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/d/dropdown

Final style note: I would address the user directly and say "You can filter by the following operations:"

2021-09-06 16:23 UTC, AshVic commented on docs/manage-migrations.md
> +| **Unlink (Delete Path)** | Unlink operations remove files under migration. |
Line 179 - the second word in parentheses is lower case but this line has title case? Maybe change for consistency to "Delete **p**ath"?

2021-09-06 16:35 UTC, lucasdigital commented on docs/manage-migrations.md
> +Filter or search for failed operations by using the *Operation type* drop-down selector on the Migration Check Report panel. The filter contains the following operations:
Oops, yes for "Operation type". Updating with all points.

2021-09-06 17:32 UTC, lucasdigital commented on docs/manage-migrations.md
> +| **Unlink (Delete Path)** | Unlink operations remove files under migration. |
Agreed! I'll double-check that these are consistent with the latest version. The version I referenced used this pattern except for **Metadata (Change Permissions)**.

2021-09-07 11:35 UTC, AshVic approved these changes
LGTM!

2021-09-07 13:16 UTC, merged