updated command-reference.md and connect-metastores.md docu-1293
WANdisco/wandisco-documentation-ldm pull request #272
Opened 2021-09-07 10:02 UTC by fi3ld

https://jira.wandisco.com/browse/DOCU-1293

2021-09-07 11:31 UTC, AshVic requested changes

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +Add a hive agent to connect to a local or remote [Google Dataproc](https://cloud.google.com/dataproc-metastore/docs) metastore using the `hive agent add dataproc` command.
Use upper case "Hive" for a trademarked product name.

Also use capital "**M**" for Metastore as it is a proper noun and product name.

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +When connecting to a remote Dataproc metastore, specify a host on the remote cluster that will be used to communicate with the local LiveData Migrator server (constrained to a user-defined port).
Same as above: this should be "Dataproc Metastore" because it is a TM'd product name.

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +A small service will be deployed on this remote host so that the hive agent can migrate data to and/or from the remote dataproc metastore.
...so that the **H**ive agent...**D**ataproc **M**etastore.

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +```text title="Add local or remote dataproc agent"
Use capital "D" **D**ataproc

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +#### Parameters for remote hive agents only
Capital **H** for **H**ive

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +* **`--host`** The host where the remote hive agent will be deployed.
Hive

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +* **`--port`** The port for the remote hive agent to use on the remote host. This port is used to communicate with the local LiveData Migrator server.
Hive

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +If you do not wish to use the `--autodeploy` function, follow these steps to deploy a remote hive agent for Apache Hive manually:
Hive agent

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +If specifying Kerberos and config path information for remote agents, ensure that the directories and Kerberos principal are correct for your chosen remote host (not your local host).
Suggestion: write "configuration path" in full - I know it is clear enough, it is just a consistent style thing.

2021-09-07 11:31 UTC, AshVic commented on docs/command-reference.md
> +All parameters are optional except `--name`, which is required to specify the existing hive agent that you wish to configure.
Hive agent

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Click Connect To Metastore.
Use bold font for UI texts. **Connect to Metastore**.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Click Connect To Metastore.
Use bold font for UI texts.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Click Save
Bold **Save**.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Specify DefaultFs Override (optional).
Bold for UI text

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Specify DefaultFs Override (optional).
Bold for UI text

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Click Save
Bold **Save**.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Click Connect To Metastore.
Bold for UI texts.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Specify DefaultFs Override (optional).
Same as previous comments...please go through the UI texts and embolden them through to line 113.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Provide the Hostname or IP Address
You don't need to capitalize Hostname or Address.

"Provide the host name or the IP address."

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Choose a Display Name
You don't need to capitalize display name.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Select Google Cloud Dataproc as the Agent type.
Remove capitals. They are only needed if something is a proper noun / product name OR if it is capitalized on the user interface and you have to copy what the user sees exactly.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Provide the Port
port

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Select the Filesystem.
filesystem

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Specify DefaultFs Override (optional).
Bold if this is a UI text you're copying.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +1. Click Save
Bold Save.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +### Connect To Metastores
Lower case for the preposition "**t**o".

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +Connect To Metastores to connect your source and target metastores.
Lower case for the preposition "**t**o".

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +| [`hive agent add dataproc`](./command-reference.md#hive-agent-add-dataproc) | Add a hive agent for a Google Cloud Dataproc metastore |
**H**ive agent

Google Cloud Dataproc Metastore - proper noun / product name requires title case.

2021-09-07 11:31 UTC, AshVic commented on docs/connect-metastores.md
> +| [`hive agent configure datapropc`](./command-reference.md#hive-agent-configure-databricks) | Change the configuration of an existing hive agent for the Google Cloud Dataproc metastore |
**H**ive  agent

Google Cloud Dataproc Metastore - proper noun / product name requires title case.

2021-09-07 11:57 UTC, fi3ld commented on docs/command-reference.md
> +Add a hive agent to connect to a local or remote [Google Dataproc](https://cloud.google.com/dataproc-metastore/docs) metastore using the `hive agent add dataproc` command.
Done

2021-09-07 15:08 UTC, fi3ld commented
> so that data can transfer between the hive agent and the remote Dataproc metastore.
Done

2021-09-08 10:01 UTC, fi3ld commented on docs/connect-metastores.md
> +Connect To Metastores to connect your source and target metastores.
@AshVic The UI button has the uppercase t. 

Connect To Metastore. 

Should I keep it upper case?

2021-09-08 10:51 UTC, merged