added new content docu-1173
WANdisco/wandisco-documentation-ldm pull request #276
Opened 2021-09-13 15:23 UTC by fi3ld

https://jira.wandisco.com/browse/DOCU-1173

2021-09-13 15:32 UTC, lucasdigital approved these changes
Looks good. Just one comment.

2021-09-13 15:35 UTC, AshVic requested changes
General comments:

Usually we should write a product name or trademarked name out in full at the beginning and then after first instance use the abbreviation. eg. Transport Layer Security (TSL) first time, and thereafter, just TSL.

Also I would be consistent when using title and sentence case in headers. There is a mix of both for level 3 headers.

One small typ further down to correct.

2021-09-13 15:35 UTC, AshVic commented on docs/configuration-ldm.md
> +| HTTP_MAX_CONNECTIONS="value" | Specifies the maximum number of keep-alive connections that are maintatined. The possible range is zero to 32768. |
Typo: maintained

2021-09-13 15:48 UTC, lucasdigital commented on docs/configuration-ldm.md
> +| HTTP_MAX_CONNECTIONS="value" | Specifies the maximum number of keep-alive connections that are maintatined. The possible range is zero to 32768. |
ooh missed that!

2021-09-13 15:48 UTC, fi3ld commented
I need to change ### Directory structure to ## Directory structure.

2021-09-14 10:00 UTC, fi3ld commented
> Line 215. We've stopped using Latin abbreviations, so I would change eg into (For example: LDM_...)
> Also, add a full stop to the line for consistency -- or remove the ones included on the other lines.

Done

2021-09-14 10:00 UTC, fi3ld commented
> I need to change ### Directory structure to ## Directory structure.

Done

2021-09-14 10:07 UTC, fi3ld commented on docs/configuration-ldm.md
> +| HTTP_MAX_CONNECTIONS="value" | Specifies the maximum number of keep-alive connections that are maintatined. The possible range is zero to 32768. |
Done

2021-09-14 10:27 UTC, AshVic requested changes
Minor changes otherwise LGTM

2021-09-14 10:27 UTC, AshVic commented on docs/configuration-ldm.md
> +#### Connecting To LiveData Migrator With Basic Authentication
Use lower case for prepositions in titles/headers: "to"

2021-09-14 10:27 UTC, AshVic commented on docs/configuration-ldm.md
> +| LDM_EXTRA_JVM_ARGS=”value” | Add extra Java arguments (for example LDM_EXTRA_JVM_ARGS=“-Dhttps.proxyHost=sub.proxy.att.com -Dhttps.proxyPort=8080”). |
Comma after "For example,"

2021-09-14 10:35 UTC, merged