mlucas-DOCU-1480
WANdisco/wandisco-documentation-ldm pull request #298
Opened 2021-11-09 15:19 UTC by lucasdigital

Fixes/improvements for the auth instructions.

Changes previewed here:
https://github.com/WANdisco/wandisco-documentation-ldm/blob/mlucas-DOCU-1480/docs/configuration-hvm.md#security

https://github.com/WANdisco/wandisco-documentation-ldm/blob/mlucas-DOCU-1480/docs/configuration-ui.md#basic-authentication-compatibility

2021-11-09 15:39 UTC, AshVic requested changes

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +   1. Encrypt a string
Add periods at the end of the list items.

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +   3. Setup LDM Basic Auth
Set up is two words if a verb.

Write LDM as liveData Migrator.

basic auth.

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +   4. Setup HVM Basic Auth
Hive Migrator basic auth.

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +   5. Setup Livedata UI LDAP authentication
Live**D**ata UI

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +   Please select an option:
We don't use "please" generally.

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +1. Select option `3. Setup LDM Basic Auth`.
Set up LiveData Migrator basic auth.

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +   1. Encrypt a string
See comments above for adding periods to list items and other edits.

2021-11-09 15:39 UTC, AshVic commented on docs/configuration-ui.md
> +1. Select option `4. Setup HVM Basic Auth`.
See above comments.

2021-11-09 15:52 UTC, lucasdigital commented on docs/configuration-ui.md
> +   1. Encrypt a string
This is a direct copy of the CLI. If I fix it then it won't match. Do I still fix it and live with the disconnect?

![Screenshot 2021-11-09 at 15 51 12](https://user-images.githubusercontent.com/8897115/140957832-576d4287-113e-4b5f-94ca-88f1f080cf5b.png)
.

2021-12-03 10:25 UTC, lucasdigital commented
I've agreed with Ashleigh that we'll remove the offending text to get these changes merged. I'll comment on INC-4209 that a doc task should be raised when the CLI tool's wording is updated.

2021-12-03 10:25 UTC, merged